### ISSUE TITLE
Incorrect timezone used in call tool

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/copyright#146]
Looks like the call tool is using CEST, while Brussels is currently in CET. 
CC @ScottDowne I remember there’s some logic around it, and that it got correctly updated in October, but maybe it broke when we hit 2018?

![image](https://user-images.githubusercontent.com/1294206/36217390-3512dce6-11a9-11e8-906f-e3e9306adbc6.png)

**Comment by ScottDowne** [comment]
Looking

**Comment by TheoChevalier** [comment]
This has been fixed (thanks Scott!)
