### ISSUE TITLE
Double check the list of phone numbers in call tool

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/copyright#148]
Initial report: https://bugzilla.mozilla.org/show_bug.cgi?id=1445911

Ross: Any chance you remember the name of the person you’ve been connected to?

@jonmozilla in case you have access to the call tool or know who has, we may want to double check the full list of phone numbers before sending any update

**Comment by rossbearman** [comment]
Thanks for moving this to the correct location Theo, I didn't find this repo while searching for somewhere to post about it.

I believe the phone number that I managed to get through on, but which no longer belongs to a committee member, was for António Marinho e Pinto.

**Comment by jonmozilla** [comment]
Thanks Theo, I'll look into this.

**Comment by jonmozilla** [comment]
Hi all, just to loop back in on this. I've updated the list of members (two
cycled off the committee, two new ones on there). I also double checked the
numbers and they're current.

Pinto is still listed as a committee member (here
<http://www.europarl.europa.eu/committees/en/juri/members.html?action=1>) –
Ross, do you have any additional information about that by any chance?

**Comment by TheoChevalier** [comment]
Thanks Jon! I have a follow up, but I will just file a new issue for that and close this one
