### ISSUE TITLE
Functionality needed for copyright site changes

### ISSUE THREAD

**Issue by jonmozilla** [mozilla/copyright#153]
- [x] Upload new phone lists in EN, DE, FR, IT, ES, PL for MEPs in Strasbourg and Brussels

- [x] Switch phone numbers from Brussels to Strasbourg on Jun 25 AND THEN BACK on Jul 2

- [x] Update copy on the page to reflect the change in circumstances

**Comment by jonmozilla** [comment]
New phone lists [in this doc](https://docs.google.com/spreadsheets/d/13jL7E-2kTFI5Hbe8RiZiwb3RBaMsjE2JIL9Bjo9fBwI/edit?ts=5b2b6857#gid=0).

**Comment by jonmozilla** [comment]
Here's the [updated page copy](https://docs.google.com/document/d/17JJsDFi2Nvob80EWMt-dVufG3BpnS3YpMusTvlKvN5o/edit?ts=5b2cb750)

**Comment by ScottDowne** [comment]
@jonmozilla not sure what is being asked for the first point. I don't think this happens in a system I'm familiar with. Do you know who manages the lists in callpower?

**Comment by ScottDowne** [comment]
@TheoChevalier I think there is a l10n component to this. I'll make the string changes in a pull request and cc you.

**Comment by alanmoo** [comment]
@jonmozilla We've got the phone numbers that were used last week (all-hands) up on [staging](http://changecopyright-org-staging.herokuapp.com/) along with the copy changes. If this is right, I can make it live as soon as I get up Monday. Next week we should figure out a more sustainable approach to this if it's something we're going to regularly be doing.

**Comment by ScottDowne** [comment]
@alanmoo Can we close this?

The second two original points are done, not sure about the status of the first.
