### ISSUE TITLE
ENV var-ize campaign IDs

### ISSUE THREAD

**Issue by alanmoo** [mozilla/copyright#155]
In lieu of a real management solution for campaign IDs, let's move them to an environmental variable so they're easier to switch up without having to go through the deploy process.

We'll need to add a variable for each language in [this file](https://github.com/mozilla/copyright/blob/a43d19fa8127814d1bbd88f9355abd1dcfb1d212/routes/campaign-ids.js), or consolidate into multiple sets of vars based on location.

**Comment by ScottDowne** [comment]
Fixed in https://github.com/mozilla/copyright/pull/156
