### ISSUE TITLE
Homepage update after campaign win

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/copyright#162]
The Parliament rejected the directive, we should now close the call tool.

Things to do:

- [x] 1. Redirect /call-now page to /
- [x] 2. Remove all “Call now” buttons (in the top nav, under the first section, and before the newsletter sign up form)
- [x] 3. Actually switch off the call tool
- [x] 4. Merge new string
- [x] 5. Replace “We’ll provide you with what to say before calling.”, “CALL NOW”, and “Call Members of the European Parliament, tell them…” with the string in https://github.com/mozilla/copyright/pull/161/files

**Comment by TheoChevalier** [comment]
@alanmoo Could you take of #3 when you’re back?

**Comment by TheoChevalier** [comment]
The rest has been fixed in https://github.com/mozilla/copyright/commit/25076e715dcbb4ae9fe2e470d70722b13dacc81c

**Comment by alanmoo** [comment]
@TheoChevalier This totally fell under my radar. What needs to happen for turning off the tool? Taking off the button, removing a page, etc?

**Comment by TheoChevalier** [comment]
@alanmoo Right now I’ve removed all the buttons and I’m redirecting /call-now to /, but I assume one could still send a phone number via a POST request to the API. So I think what we need is to switch off the call tool from its admin console (if there’s such a thing).

Not sure if you have that access or if @jonmozilla has it. Or if it’s on Chris

**Comment by alanmoo** [comment]
I've paused the campaigns from the Call Power backend.
