### ISSUE TITLE
First/Last name not passed to basket

### ISSUE THREAD

**Issue by cadecairos** [mozilla/copyright#61]
We need to pass the `firstName` and `lastName` fields submitted by the form to sawmill. This should happen here: https://github.com/mozilla/copyright/blob/2664f84165960283567a21f7331bd54a6b86068a/routes/signup.js#L5-L13

cc/ @stephaniemcv @ScottDowne

**Comment by stephaniemcv** [comment]
Actually, this might not be a blocker at all. Because all that info is going into a sheet, yes? We can update First Name, Last Name at that time the we import signatures.

**Comment by hannahkane** [comment]
My understanding is there's not a sheet for this, since it's just collecting email sign-ups; it's not a petition. @ScottDowne to confirm.

**Comment by stephaniemcv** [comment]
Oh yeah, you're right. I keep thinking Copyright is a petition again.

**Comment by ScottDowne** [comment]
Good catch.

1. We can fix this before it's a problem in copyright.
2. Open data ALSO has this bug. In that case, we very much need the sheets to get the names.

**Comment by ScottDowne** [comment]
Should be fixed in copyright.

**Comment by stephaniemcv** [comment]
I will qa right now.

**Comment by stephaniemcv** [comment]
Nope. They still didn't pass through.

**Comment by ScottDowne** [comment]
It probably isn't on production yet. And staging doesn't use prod
salesforce. I'll ping you when it's ready.

**Comment by stephaniemcv** [comment]
Sounds good!

**Comment by stephaniemcv** [comment]
Confirm. First Name and Last Name is passing. Locale is correctly checking language and source url is passing as well.

**Comment by ScottDowne** [comment]
Cool, thanks.
